---
# This playbook contains common customizations for all machines

#- name: Run yum update -y
#  yum: name=* state=latest
#  sudo: yes

- name: Copy bash inputrc to remote host
  tags: local,bash
  copy: src=files/inputrc dest=/root/.inputrc

- name: Set current LC_CTYPE 
  tags: local,bash
  lineinfile:
     dest=/root/.bashrc 
     line='export LC_CTYPE=en_DK.iso88591'
     state=present
     regexp='.*LC_CTYPE=.*'

- name: Let's check that /scratch is world-writable
  tags: mount
  file: 
    path: "/scratch"
    mode: 1777
    state: directory
  when: (inventory_hostname in groups.compute or inventory_hostname in groups.login)

# install some "missing" packages
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Propagate install-nodes rsa-key to hosts
  tags: local
  when: inventory_hostname not in groups.admin
  authorized_key: user=root key="{{ lookup('file', 'files/install_rsa.pub') }}"

- name: Set tmp-file cleaning interval to 30 days
  tags: local,tmp
  template: src=tmp.conf dest=/etc/tmpfiles.d/tmp.conf owner=root group=admin mode=0644

#- name: Add mgmt-adresses to /etc/hosts.local
#  tags: local,dns
#  template: src=hosts.local.j2 dest=/etc/hosts.local owner=root group=admin mode=0644
#  with_items: groups.compute


#- name: create directory for ansible custom facts
#  file: state=directory recurse=yes path=/etc/ansible/facts.d

#- name: find ib firmware version for ansible
#  shell:

#- name: re-read facts after adding custom fact
#  setup: filter=ansible_local

- name: Add local modulepath to /etc/profile.d
  tags: local
  when: inventory_hostname in groups.compute
  copy: src=files/tut-modules.sh dest=/etc/profile.d/tut-modules.sh


