---
- name: Install net-tools for old ifconfig
  tags: local,packages
  yum: name=net-tools state=installed

- name: Install bind-utils for e.g. dig
  tags: local,packages
  yum: name=bind-utils state=installed

- name: Install mlocate
  tags: local,packages
  yum: name=mlocate state=installed

- name: Install zsh
  tags: local,packages
  yum: name=zsh state=installed


