---
# Loading vars
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Install DHCP server
- name: Install the required  packages in Redhat derivatives
  yum: name={{ dhcp_server_package }} state=installed
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ dhcp_server_package }} state=installed update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install the required packages in ArchLinux derivatives
  pacman: name={{ dhcp_server_package }} state=installed update_cache=yes
  when: ansible_os_family == 'Archlinux'

- name: create a /etc/dhcp/dhcpd.d directory
  file: state=directory path=/etc/dhcp/dhcpd.d owner=root group=admin mode=0750

- name: create a dummy nodes.conf file
  file: state=touch path=/etc/dhcp/dhcpd.d/nodes.conf owner=root mode=0644
  changed_when: false

- name: create a dummy static.conf file
  file: state=touch path=/etc/dhcp/dhcpd.d/static.conf owner=root mode=0644
  changed_when: false

# Generate configuration
- name: Generate dhcpd.conf
  template: src=dhcpd.conf.j2 dest={{ dhcp_server_config }} owner=root group=root mode=0644 validate='/usr/sbin/dhcpd -t -cf %s'
  notify:
    - restart dhcpd

# Generate service configuration
- name: Generate DHCP service conf
  template: src=service.conf.{{ ansible_os_family }}.j2 dest={{ dhcp_service_config }} owner=root group=root
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
  notify:
    - restart dhcpd

# Enable DHCP server
- name: Start the dhcp services DHCP
  service: name={{ dhcp_service }} enabled=yes state=started 
