---
# Tasks for only admin-node
- name: Copy Idrac & ilo node-reset -script to admin-node
  tags: admin
  copy: src=node_reset.exp mode=0755 dest=/usr/local/sbin

- name: Copy Idrac & ilo node-poweron -script to admin-node
  tags: admin
  copy: src=node_poweron.exp mode=0755 dest=/usr/local/sbin

- name: Copy Idrac & ilo node-poweroff -script to admin-node
  tags: admin
  copy: src=node_poweroff.exp mode=0755 dest=/usr/local/sbin

- name: Copy Idrac & ilo node-console -script to admin-node
  tags: admin
  copy: src=node_console.exp mode=0755 dest=/usr/local/sbin

- name: Copy expect-admin-library to admin-node
  tags: admin
  copy: src=library.exp dest=/usr/local/sbin

- name: Copy Dell Perccli.rpm to fileservers
  tags: admin,mgmt
  copy: src=files/dell-dset-lx64-3.7.0.219.bin dest=/root/Dell

- name: populate /etc/hosts file with mgmt-addresses
  lineinfile: 
        dest=/etc/hosts 
        regexp='^{{ hostvars[item].mgmt_ip_addr }} {{ hostvars[item].pxe_name }}-ilo' 
        line="{{ hostvars[item].mgmt_ip_addr }} {{ hostvars[item].pxe_name }}-ilo" 
        state=present
  when: hostvars[item].mgmt_ip_addr is defined 
  with_items: "{{groups['compute'] + groups['nfs'] + groups['login']}}" 
# groups.production
  tags: local,mgmt

- name: Copy admin-www-home to admin-node
  tags: admin
  copy: src=files/admin-home.html dest=/usr/local

- name: Set admin-home as default homepage for firefox
  tags: admin
  lineinfile: dest=/usr/lib64/firefox/defaults/preferences/all-redhat.js regexp='^pref\("browser.startup.homepage"' 
         line='pref("browser.startup.homepage",            "data:text/plain,browser.startup.homepage=file:///usr/local/admin-home.html");'
#  copy: src=files/mozilla.cfg dest=/usr/lib64/firefox/

- name: Disable firefox automatic search from url-bar
  tags: admin
  lineinfile: dest=/usr/lib64/firefox/defaults/preferences/all-redhat.js regexp='^pref\("browser.startup.homepage"' 
         line='pref("keyword.enabled",            "data:text/plain,browser.startup.homepage=file:///usr/local/admin-home.html");'
