---
- name: testinki task
  tags: bash
  command: uname -a 
  register: my_uname

- name: Create ssh-key to root-user
  tags: admin
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: Copy useradm scripts to install node
  tags: useradm
  copy: src=files/admin/{{ item }} dest=/usr/local/sbin mode=0755
  with_items:
    - add-sshkey.sh
    - create_user.sh
    - update-mailing-list.sh
    - user_account_created.sh

- name: Copy necessary configs to /usr/local/etc
  tags: useradm
  copy: src=files/admin/{{ item }} dest=/usr/local/etc mode=0440 group=admin
  with_items:
    - ldap.key
    - tcsc-useraccount-draft.txt
    - tcsc-useraccount_ready.txt

- name: fetch the generated rsa-key-public to localhost
  tags: admin
  fetch: >
        src=".ssh/id_rsa.pub" dest="files/install_rsa.pub"
        owner=mmoa group=ssh_keys mode=0640 backup=no 
        validate_checksum=yes fail_on_missing=yes
        flat=yes
        
