---
- name: Make ttyS0 conf from template
  command: cp /usr/lib/systemd/system/serial-getty@.service /etc/systemd/system/serial-getty@ttyS0.service
  args:
    creates: /etc/systemd/system/serial-getty@ttyS0.service

- name: Add autologin to ttyS0 terminal
  lineinfile: 
    name: "/etc/systemd/system/serial-getty@ttyS0.service"
    regexp: '^ExecStart=-/sbin/agetty --keep-baud'
    line: 'ExecStart=-/sbin/agetty -a root --keep-baud 115200,38400,9600 %I $TERM'
    state: present
	notify: reload serial-console@ttyS0

- name: Symlink our terminal-conf to use
  file: 
    path: /etc/systemd/system/getty.target.wants/serial-getty@ttyS0.service
    state: link
    src: /etc/systemd/system/serial-getty@ttyS0.service



